[2023-11-15T14:46:43.653+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_github_to_gcs_dag/run_id=manual__2023-11-15T14:46:41.219751+00:00/task_id=download_dataset_task permission to 509
[2023-11-15T14:46:43.684+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_github_to_gcs_dag/run_id=manual__2023-11-15T14:46:41.219751+00:00/task_id=download_dataset_task permission to 509
[2023-11-15T14:46:43.710+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_github_to_gcs_dag.download_dataset_task manual__2023-11-15T14:46:41.219751+00:00 [queued]>
[2023-11-15T14:46:43.719+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_github_to_gcs_dag.download_dataset_task manual__2023-11-15T14:46:41.219751+00:00 [queued]>
[2023-11-15T14:46:43.720+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-15T14:46:43.734+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-11-15 14:46:41.219751+00:00
[2023-11-15T14:46:43.741+0000] {standard_task_runner.py:57} INFO - Started process 2682 to run task
[2023-11-15T14:46:43.744+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_github_to_gcs_dag', 'download_dataset_task', 'manual__2023-11-15T14:46:41.219751+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/data_github_to_gcp.py', '--cfg-path', '/tmp/tmp5owg4i8r']
[2023-11-15T14:46:43.747+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask download_dataset_task
[2023-11-15T14:46:43.762+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-11-15T14:46:43.799+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=data_github_to_gcs_dag/run_id=manual__2023-11-15T14:46:41.219751+00:00/task_id=download_dataset_task permission to 509
[2023-11-15T14:46:43.802+0000] {task_command.py:416} INFO - Running <TaskInstance: data_github_to_gcs_dag.download_dataset_task manual__2023-11-15T14:46:41.219751+00:00 [running]> on host 2952db3161f1
[2023-11-15T14:46:43.884+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_github_to_gcs_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T14:46:41.219751+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T14:46:41.219751+00:00'
[2023-11-15T14:46:43.886+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-15T14:46:43.887+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL https://github.com/Georgeshermann/getting_data/blob/main/movies.csv > /opt/***/movies.csv']
[2023-11-15T14:46:43.901+0000] {subprocess.py:86} INFO - Output:
[2023-11-15T14:46:43.917+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: github.com
[2023-11-15T14:46:43.918+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2023-11-15T14:46:43.931+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2023-11-15T14:46:43.935+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_github_to_gcs_dag, task_id=download_dataset_task, execution_date=20231115T144641, start_date=20231115T144643, end_date=20231115T144643
[2023-11-15T14:46:43.953+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 87 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 6.; 2682)
[2023-11-15T14:46:43.998+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T14:46:44.022+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
